apiVersion: v1
kind: ConfigMap
metadata:
  name: log-generator-config
data:
  logs_config.json: |
    {
        "interval": 1,
        "logs": [
            {
                "message": "User authentication successful for user_id: 12345",
                "level": "INFO"
            },
            {
                "message": "Database connection established successfully",
                "level": "INFO"
            },
            {
                "message": "API request completed: GET /api/users - Status: 200",
                "level": "INFO"
            },
            {
                "message": "Cache miss for key: user_profile_12345",
                "level": "WARNING"
            },
            {
                "message": "High memory usage detected: 85% of available memory in use",
                "level": "WARNING"
            },
            {
                "message": "Failed to connect to external service: Connection timeout",
                "level": "ERROR"
            },
            {
                "message": "Database transaction failed: Deadlock detected",
                "level": "ERROR"
            },
            {
                "message": "Critical system failure: Unable to initialize core services",
                "level": "CRITICAL"
            },
            {
                "message": "Debug: Processing request with parameters: {id: 12345, type: 'user'}",
                "level": "DEBUG"
            },
            {
                "message": "Debug: Memory allocation details - Used: 512MB, Free: 1024MB",
                "level": "DEBUG"
            },
            {
                "message": "System health check passed successfully",
                "level": "INFO"
            },
            {
                "message": "Backup process started: Creating system snapshot",
                "level": "INFO"
            }
        ]
    } 